name: character_viewer
description: "View characters from the hit shows The Simpsons or The Wire"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-417.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  built_collection: ^5.1.1
  built_value: ^8.6.2
  logging: ^1.2.0
  rxdart:
    git:
      url: git@github.com:kismet-/rxdart.git
      ref: main
  inject_annotation: ^1.0.0-alpha.3
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  video_player: ^2.7.2
  mockito: ^5.4.2
  test: ^1.24.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: ^8.6.2
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  inject_generator: ^1.0.0-alpha.3

dependency_overrides:
  rxdart:
    git:
      url: git@github.com:kismet-/rxdart.git
      ref: main


flutter:
  uses-material-design: true
  assets:
    - assets/audio/